---
title: "Taller_1"
author: "Andres David Gomez B"
date: "11 de febrero de 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Horner






```{r }
# Horner
rm(list=ls())
horner <- function(p,n,x) {
  y<-p[c(1)]
  i<-1
  iter<-0
  while (i < n+1) {
    y<-x*y+p[c(i+1)]
    i<-i+1
    iter<-iter+2
  }
  cat("RES: ",y,"\n")
  cat("Operaciones: ",iter,"\n")
  iter<-0
  i<-n
  j<-1
  der<-0
  while (i > 0) {
    der[c(j)]<-(p[c(j)]*i)
    i<-i-1
    j<-j+1
  }
  i<-1
  y<-der[c(1)]
  while (i < n) {
    y<-x*y+der[c(i+1)]
    i<-i+1
    iter<-iter+2
  }
  cat("RES derivada : ",y,"\n")
  cat("Operaciones derivada: ",iter,"\n")
}
p<-c(2,0,-3,3,-4)
horner(p,4,-2)
cat("*************************" ,"\n")
p<-c(7,6,-6,0,3,-4)
horner(p,5,3)
cat("*************************" ,"\n")
p<-c(-5,0,3,0,2,-4,0)
horner(p,6,-1)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

